### ISSUE TITLE
Error: 'std::vector' has not been declared

### ISSUE THREAD

**Issue by Stromberg90** [fragcolor-xyz/nimline#4]
I tried to work with mini-yaml https://github.com/jimmiebergmann/mini-yaml

here is the code
```
import nimline

cppfiles("Yaml.cpp")
defineCppType(YamlNode, "Yaml::Node", "Yaml.hpp")

let yaml_input: cstring = """
men: [John Smith, Bill Jones]
women:
  - Mary Smith
  - Susan Williams
"""

var root: YamlNode
```
I compiled it like this `nim cpp .\main.nim`
and I get this error after `error: 'std::vector' has not been declared`

**Comment by jwollen** [comment]
This seems to be a mini-yaml problem. I'm not sure how it's supposed to be used, but it nowhere includes `<vector>`.
Adding `#include <vector>` in `yaml.cpp` makes it compile fine.

**Comment by Stromberg90** [comment]
I see, I should have checked that first :)
